from typing import Callable, Tuple

class Window:
    size: Tuple[int, int]
    def on_update(self, update: Callable) -> Callable: ...

class Loader:
    def load_opengl_function(self, name: str) -> int: ...

class Audio:
    pass

def init() -> None: ...
def run() -> None: ...
def get_window() -> Window: ...
def get_loader() -> Loader: ...
def get_audio() -> Audio: ...
